### ISSUE TITLE
Intersection creates degenerate triangle

### ISSUE THREAD

**Issue by Azorlogh** [iShape-Rust/iOverlay#11]
This intersection produces a triangle where all three points have the same coordinate:
```
let path_a: F32Path = vec![
    F32Point::new(48.239437, -54.70892),
    F32Point::new(47.195786, -55.457626),
    F32Point::new(46.968903, -56.886974),
    F32Point::new(36.532383, -55.07193),
    F32Point::new(37.961735, -46.7454),
    F32Point::new(40.02635, -47.085724),
    F32Point::new(40.094414, -46.7454),
    F32Point::new(44.51859, -47.516796),
    F32Point::new(44.473213, -47.83443),
    F32Point::new(48.398254, -48.51507),
    F32Point::new(48.10331, -49.9898),
    F32Point::new(48.874702, -50.965385),
];

let path_b = vec![
    F32Point::new(48.398247, -48.515068),
    F32Point::new(48.10331, -49.989796),
    F32Point::new(44.473213, -47.834427),
];

let mut overlay = F32Overlay::new();
overlay.add_path(path_a, ShapeType::Subject);
overlay.add_path(path_b, ShapeType::Clip);
let graph = overlay.into_graph(FillRule::EvenOdd);
let shapes = graph.extract_shapes(OverlayRule::Intersect);
println!("{shapes:?}");
```
This generates these shapes, where the first path is the aforementioned triangle:
```
[[[F32Point { x: 44.473213, y: -47.834427 }, F32Point { x: 44.473213, y: -47.834427 }, F32Point { x: 44.473213, y: -47.834427 }]], [[F32Point { x: 44.47322, y: -47.83443 }, F32Point { x: 48.398247, y: -48.51507 }, F32Point { x: 48.10331, y: -49.989796 }]]]
```

**Comment by Azorlogh** [comment]
Also interesting: using `extract_shapes_min_area` instead returns only the degenerate triangle, and not the valid one :thinking: 
`[[[F32Point { x: 44.473213, y: -47.834427 }, F32Point { x: 44.473213, y: -47.834427 }, F32Point { x: 44.473213, y: -47.834427 }]]]`

**Comment by NailxSharipov** [comment]
Hi AzorLogh.
Thanks for sharing this test case — it's indeed an interesting one!
It seems like `f32` precision is not enough to represent it in `i32`. In `i32` the result is:
```
[[[
    IntPoint { x: 237520896, y: 534422528 },
    IntPoint { x: 237520967, y: 534422516 },
    IntPoint { x: 237520963, y: 534422488 }
]],
[[
    IntPoint { x: 237522114, y: 534421805 },
    IntPoint { x: 764329919, y: 443068093 },
    IntPoint { x: 724744192, y: 245133824 }
]]]
```
With `extract_shapes_min_area` is a bug the condition is inversed. I made a fix in 1.7.3 which fix it.
As for the `f32` results, a potential solution could be to implement a normalization function. This function would convert the `f32` results back to `i32`, clean up any degenerate edges, and then convert back to `f32`. Since this approach wouldn't significantly impact performance, I’m considering how best to apply it, possibly as an optional or as a default.

**Comment by NailxSharipov** [comment]
In 1.8.0 I added a new Float api which normalize the result by removing degenerated points and edges.
It is switched on by default for f32 and off for f64. It can be adjusted by Filter api:

pub fn overlay_with_filter_and_solver(self, overlay_rule: OverlayRule, fill_rule: FillRule, filter: ContourFilter<T>, solver: Solver) -> Shapes<P>;

pub struct ContourFilter<T> {
    pub min_area: T,
    pub simplify: bool,
}

impl<T: FloatNumber> Default for ContourFilter<T> {
    fn default() -> Self {
        // f32 precision is not enough to cover i32
        let simplify = T::bit_width() <= 32;
        ContourFilter { min_area: T::from_float(0.0), simplify }
    }
}

**Comment by Azorlogh** [comment]
Awesome, thanks a lot!
