### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by LagradOst** [iShape-Rust/iOverlay#2]
I get that you have some interactive docs in https://ishape-rust.github.io/iShape-js/overlay/stars_demo.html but right now you have ZERO comments in your code. When I use a lib it would be nice to at least know just a line or two what a function does or what an enum is. Like wth is ShapeType?? and what is the difference between Subject and Clip??

A simple /** explain here */ or /// before the enum or function would make it much easier to follow when coding as you get that as an editor hint. It does not need to be an essay, but just something.

**Comment by NailxSharipov** [comment]
Yes, I agree that comments are super important and it's on my list to do.
The project is still on development and api is not stable. But some things like this enum is pretty stable so I will do it soon.

Thanks for you attention and feedback.

**Comment by NailxSharipov** [comment]
I've added description to the most important public api
