### ISSUE TITLE
Output interpretation

### ISSUE THREAD

**Issue by TarVK** [iShape-Rust/iOverlay#3]
It isn't fully clear to me how to interpret the output of the algorithm. It's a `Vec<Vec<Vec<F64Point>>>`, and I understand it represents a set of polygons, that can have holes. I am not familiar with the convention for representing holes though. Is the following assumption correct:
- The outer Vec represents a set of shapes
- Each shape Vec represents a collection of polygons, where the first polygon is the outer boundary, and all subsequent polygons are holes in this boundary
- Each polygon Vec represents a collection of points, where every two consecutive points (cyclically) make up the boundary edge of the polygon

I think it would be worth being very eplicit about this in the docs/comments, for people that are not familiar with the conventions. 

But it's worth mentioning that overall this library looks really great!

**Comment by NailxSharipov** [comment]
That's absolutely correct.
One more thing I can add is that all outer boundary paths have a clockwise order, and all holes have a counterclockwise order.

I agree that this part must be explained in the documentation. I will add this on my list to do.

Thanks for your feedback.

**Comment by NailxSharipov** [comment]
Added more detailed explanation to the API documentation.
