### ISSUE TITLE
Split a polygon by linestrings

### ISSUE THREAD

**Issue by dabreegster** [iShape-Rust/iOverlay#7]
How hard would it be to support [splitting](https://postgis.net/docs/ST_Split.html) a polygon by one or more linestrings? I could approximate this today by first buffering the linestring into a very thin polygon (using something like https://github.com/jbuckmccready/cavalier_contours) and then using `difference`. But it'd be quite useful to avoid the buffering step and have the resulting pieces fit together without any gaps.

**Comment by NailxSharipov** [comment]
Currently, structures like LineString are not supported. I have some ideas on how to implement them, but it will take time to explore fully, so I don't expect to add this feature in the near future.

For now, you can achieve this by creating a thin polygon with 2px height. It's a dirty hack, but must work.

**Comment by dabreegster** [comment]
Thanks for the quick reply. I've been thinking about ways of implementing this, and have come up with:

1) Brute-force look for all intersections between all of the input linestrings and the polygon's boundary. Split each of them into smaller linestrings when those intersections happen. (An r-tree can speed up the search) 
2) Create an undirected graph from all of the linestrings
3) Find all cycles in the graph, collecting the points in order as it goes. Each cycle is a resulting polygon. This could be done by visiting every unvisited edge in the graph, then figuring out how to consistently trace either clockwise or counter-clockwise.

I think I've attempted some parts of this before, but gotten stuck on floating point issues (from bad input geometry with self-intersections; but the application I have in mind now would be much better) and the clockwise ordering. But reading through https://ishape-rust.github.io/iShape-js/overlay/extract/extract_shapes.html and your use of fixed-precision vectors, I think something like this could work. As I have time, I'll try something like this and keep you posted, in case the result is useful to adapt here.

**Comment by NailxSharipov** [comment]
Current logic is using sweep line algorithm for splitting edges. No need to fix it.
It operates with:

```
pub(crate) struct Segment {
    pub(crate) x_segment: XSegment,
    pub(crate) count: ShapeCount,
    // need to add cutting marker 
}
```

a < b always! (a.x < b.x || a.x == b.x && a.y < b.y)
```
pub(crate) struct XSegment {
    pub(crate) a: IntPoint,
    pub(crate) b: IntPoint,
}
```

winding count
```
pub struct ShapeCount {
    pub(crate) subj: i32,
    pub(crate) clip: i32,
}

```
after splitting and filling steps we get a graph:

```
pub struct OverlayGraph {
    pub(crate) solver: Solver,
    pub(crate) nodes: Vec<OverlayNode>,
    pub(crate) links: Vec<OverlayLink>,
}

pub(crate) struct OverlayLink {
    pub(crate) a: IdPoint,
    pub(crate) b: IdPoint,
    pub(crate) fill: SegmentFill,
}

pub type SegmentFill = u8;
```
And for `fill` we use only first 4 bits. We can use 5th bit as slicing marker.

Next, we need to rework `OverlayGraph::extract_shapes_min_area`, with a focus on the sub-function `find_nearest_counter_wise_link_to`. It doesn’t seem like a huge task, and I’ll aim to implement it next week.

This could be useful both for slicing and filtering such lines.

However, I’m not sure what else we can do with these LineStrings. May be I’m missing some use cases, which makes it hard for me to plan an optimal API for them.

**Comment by dabreegster** [comment]
I prototyped over the weekend and got an [edge splitter](https://github.com/nptscot/editor/blob/main/backend/src/split_lines.rs) to work, and started on [extracting faces from a planar graph](https://github.com/nptscot/editor/blob/main/backend/src/planar_graph.rs), but there are bugs with sorting the edges clockwise (that I know how to fix, just need more time). I don't understand iOverlay well enough to follow most of what you wrote, but I'm sure your implementation is going to wind up much more general and nice.

I can help with use cases though. In https://github.com/a-b-street/ltn and some other applications (mesh density image from X), a large area needs to be partitioned by a bunch of "main" roads and "severances" such as rivers and railways:
![image](https://github.com/user-attachments/assets/2e494586-8c3a-4912-a7e3-c2c7908c597a)
![image](https://github.com/user-attachments/assets/22024ea2-bd92-4565-a5a8-77e743b902a2)
So given a large polygon covering the whole area (sometimes just a bounding box, sometimes a more detailed shape) and a bunch of linestrings representing segments of roads and rivers, split the polygon into smaller pieces. A final API like `split_polygon(Polygon, Vec<LineString>) -> Vec<Polygon>` is my aim. I've attempted calculating this kind of thing directly on a rich graph structure from the road network, but a road network isn't always a planar graph (when bridges / tunnels are involved) and the method is quite brittle. I've since recognized the usefulness of just doing this at the geometric level, then later relating it back to the road network structure.

A use case for #6, clipping a linestring to a polygon (or maybe it's easier to frame this as "split a linestring by a polygon", `fn split_linestring(LineString, Polygon) -> Vec<LineString>`) is simpler. In some analyses I work on, a road segment needs to be assigned to a census zone. Most roads are fully within one zone, but sometimes they cross, and it's useful to either pick the zone that contains most of the road by length, or to split the road into two pieces.

If it's helpful to generate some "real world" inputs, I can do it easily from OpenStreetMap data from different places. If so, I assume Euclidean space is necessary. Is GeoJSON (with Euclidean coordinates) a useful format for you to work with, or do you prefer something else for encoding lists of points?

**Comment by dabreegster** [comment]
Edit: it's kind of a diversion, but if you'd like to explore my prior approach of tracing around road boundaries and gluing them together to make large areas, it's still online:
1) https://play.abstreet.org/0.3.49/abstreet.html?--dev
2) Press Ctrl+D to enter a debug mode
3) Press Ctrl+B to enter "blockfinding" mode
4) Play around with merging adjacent blocks
![image](https://github.com/user-attachments/assets/6973afe2-86fd-496b-9941-f41246b16311)

This approach of building up areas "bottom-up" is unfortunately brittle. The same problems can be solved by dividing a large area by the "important" linestrings, and that problem might be very nicely solvable here

**Comment by NailxSharipov** [comment]
Thanks to your example, I could better understand the problem. I tried various approaches and concluded that the current graph structure isn't suited for this task.

Here you can see what is impossible in existing graph. To address this, I’ve added a new `StringGraph` that can more precisely handle these cases and extract shapes accurately.
![string_graph](https://github.com/user-attachments/assets/6789d3e3-9d8b-4d5c-b13e-c0442a27d046)

For slicing, there are now two approaches:

Using `StringOverlay` directly:

```rust
let mut overlay = F32StringOverlay::new();
overlay.add_shape_path(vec![
    F32Point::new(-10.0, -10.0),
    F32Point::new(-10.0, 10.0),
    F32Point::new(10.0, 10.0),
    F32Point::new(10.0, -10.0),
]);

overlay.add_string_line([F32Point::new(0.0, -15.0), F32Point::new(0.0, 15.0)]);

let graph = overlay.into_graph(FillRule::NonZero);
let shapes = graph.extract_shapes(StringRule::Slice);
```


Using the `Slice` trait for a more concise approach:

```rust
let shapes = [
    F32Point::new(-10.0, -10.0),
    F32Point::new(-10.0, 10.0),
    F32Point::new(10.0, 10.0),
    F32Point::new(10.0, -10.0),
].slice_by_line([F32Point::new(0.0, -15.0), F32Point::new(0.0, 15.0)], FillRule::NonZero);
```
I've also added several random tests, so the API should be stable, but I haven’t had the chance to test it in real-time. Since all my apps are in Swift, I can’t directly test this in Rust. It might be time to consider building a Rust demo app for easier testing.

**Comment by dabreegster** [comment]
[Screencast from 08-10-24 17:19:45.webm](https://github.com/user-attachments/assets/7d851222-01e9-486c-b1a4-8b6a99f4140f)
OK wow, thank you **so much**. First try with a trivial amount of code to [integrate geo](https://github.com/nptscot/editor/blob/6b0eae343b54e285383398834696d11db73cc6cc/backend/src/mesh_density.rs#L72) with iOverlay, and I'm getting perfect results. This is a game-changer for my work; I need to revisit all of the places where I've been working around a lack of stable boolean operations in Rust. Absolutely incredible!

> It might be time to consider building a Rust demo app for easier testing.

Assuming the [shapes editor](https://ishape-rust.github.io/iShape-js/overlay/shapes_editor.html) is using Rust-as-WASM, I could imagine some more test cases and controls here to play with both polygons and linestrings

**Comment by NailxSharipov** [comment]
Hey, I'm really glad to hear that it's working well with the real data, and it's awesome to know you're seeing such positive results!

Do you think the API is well-designed overall? I tried several approaches before settling on this one.

A ShapeEditor app in Rust is on my to-do list. Once that’s done, it should make testing the API much easier.

**Comment by dabreegster** [comment]
> Do you think the API is well-designed overall? I tried several approaches before settling on this one.

The only confusing point for me is how "raw" the types are. A polygon is represented as a `Vec<Vec<F64Point>>`. Some lightweight wrapper types could be helpful. Some possible inspiration could be the `geo` integration that @michaelkirk drafted in https://github.com/georust/geo/tree/mkirk/i-overlay. I don't know if it's so necessary to introduce more complex types in this API though; it kind of depends on what other types of end-user projects want. For most of my purposes, I'll probably use Michael's geo wrappers

**Comment by NailxSharipov** [comment]
In **1.8.0** I introduced a new Float api which allow to work with user data directly without any wrappers.

```rust
#[derive(Clone, Copy, Debug)]
struct CustomPoint {
  x: f32,
  y: f32,
}

impl FloatPointCompatible<f32> for CustomPoint {
  fn from_xy(x: f32, y: f32) -> Self {
    Self { x, y }
  }

  fn x(&self) -> f32 {
    self.x
  }

  fn y(&self) -> f32 {
    self.y
  }
}

let polygon = [
    CustomPoint { x: 1.0, y: 1.0 },
    CustomPoint { x: 1.0, y: 4.0 },
    CustomPoint { x: 4.0, y: 4.0 },
    CustomPoint { x: 4.0, y: 1.0 },
];

let slicing_line = [
    CustomPoint { x: 3.0, y: 5.0 },
    CustomPoint { x: 2.0, y: 2.0 },
    CustomPoint { x: 3.0, y: 3.0 },
    CustomPoint { x: 2.0, y: 0.0 },
];

let result = polygon.slice_by(&slicing_line, FillRule::NonZero);

println!("result: {:?}", result);
```
